In [22]:
import numpy as np
import numpy.linalg as la
import matplotlib.pyplot as plt
import scipy.interpolate as interp

% matplotlib inline

We want to solve the following BVP:
\begin{equation}
q + u' = 0\\
q' = f\\
u(0) = \alpha  \\
u(L) = \beta
\end{equation}

We will divide the unit interval into $N_K$ elements, each of which will have a local solver.  We must solve the following weak formulation:
\begin{align}
(q,v)_K - (u,v')_K = u(x_{i-1})v(x_{i-1}) - u(x_i)v(x_i) \hspace{3mm} \forall v \in V\\
-(q,w')_K + q(x_i)w(x_i) - q(x_{i-1})w(x_i) = (f,w)_K   \hspace{3mm} \forall w \in W
\end{align}


In [5]:
L = 1 # length of interval
Nk = 3 # number of elements
Ni = Nk - 1 # number of interfaces
h = L/Nk  # size of each element ---- h/2 will be geometric factor when computing integrals on reference element

# try equal order polynomials now
Ne = 3   # number of nodes in an element (including endpoints)


In [66]:
# construct local basis functions

def lagrange_basis(degree):
    Ne = degree + 1
    z1 = []
    z2 = []
    xi = np.linspace(-1,1,Ne)
    
    for k in range(Ne):
        w = np.zeros_like(xi)
        w[k] = 1.0
        p = interp.lagrange(xi,w)
        z1.append(p)
        z2.append(np.polyder(p))
        
    return z1,z2


def phi_j_phi_i_ref(degree,nodes,weights,poly):
    A = np.zeros((degree+1,degree+1))
    for i in range(degree +1):
        for j in range(i,degree+1):
            A[i,j] = np.sum(weights*poly[j](nodes)*poly[i](nodes))
    
    A = A + A.T - np.diag(np.diag(A))
    return A

In [67]:
z1,z2 = lagrange_basis(2)
nodes,weights = np.polynomial.legendre.leggauss(3)
phi_j_phi_i_ref(2,nodes,weights,z1)

array([[ 0.26666667,  0.13333333, -0.06666667],
       [ 0.13333333,  1.06666667,  0.13333333],
       [-0.06666667,  0.13333333,  0.26666667]])

In [61]:
np.polynomial.legendre.leggauss?

In [51]:
degree = 2
gauss_nodes = degree + 1
nodes,weights = np.polynomial.legendre.leggauss(gauss_nodes)

In [53]:
nodes

array([-0.77459667,  0.        ,  0.77459667])

In [16]:
z = []
def f(x):
    return x**2

z.append(f)
def f(x):
    return x + 1

z.append(f)

In [20]:
np.linspace(-1,1,2)

array([-1.,  1.])

In [24]:
xi = np.linspace(0,1,3)
w = np.array([1.0, 0.0, 0.0])
p = interp.lagrange(xi,w)

In [25]:
p(xi)

array([ 1.,  0.,  0.])

In [48]:
gamma, dgamma = lagrange_basis(1)

In [49]:
gamma

[poly1d([-1.,  1.]), poly1d([ 1.,  0.])]

In [39]:
z[1]

poly1d([ 1.,  0.])

In [41]:
np.polyder(z[0])

poly1d([-1.])